---
abstract: 'SGML to PYX parser.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 1.02
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SGML-PYX
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.06
  Encode: 0
  Error::Pure: 0.22
  PYX: 0.03
  PYX::Utils: 0.03
  Tag::Reader::Perl: 0.01
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SGML-PYX
  homepage: https://github.com/tupinek/SGML-PYX
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/SGML-PYX
version: '0.01'
